### ISSUE TITLE
How can I use this code for my realsense rs305?

### ISSUE THREAD

**Issue by timeanddoctor** [sjnarmstrong/gray-code-structured-light#1]
Dear Professor:

How can I use this code for my realsense rs305?

**Comment by sjnarmstrong** [comment]
The majority of this code is aimed to create 3D scans from a camera and projector. The use of the Kinect was just to validate the scans that were taken. 
The OpenNI packages were used to capture data from the Kinect. As far as I am aware this also works on the realsense devices but is not the intention of this project. More information could be found here:
https://pypi.org/project/openni/
