### ISSUE TITLE
Can I reproject the texture to the medel?

### ISSUE THREAD

**Issue by LiZhenzhuBlog** [sjnarmstrong/gray-code-structured-light#2]
I getted the calibration between a depth camera and a projector. I have a 3d model captrued from a intel realsense camera realtime.
So, How can I reproject the texture to the medel by this code?
Could you help me, Thanks.

**Comment by sjnarmstrong** [comment]
This project deals with points and not meshes. But if you want to get the associated color value for each point in your depth image, the best approach to my knowlage is to calibrate both your depth an color sensors. This can be done with the use of opencv. The Intrinsics and extrinsic a can then be used to forward project the depth into real world coordinates. This can then be back-projected to the color image to determine which color pixels are associated with each point.
